# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title computing the MSE
#' @description computing the MSE
#' @param beta coefficient vector
#' @param est estimator
#' @param X_test test dataset
#' @export
mse_fun <- function(beta, est, X_test = NULL) {
    .Call('_SA24204175_mse_fun', PACKAGE = 'SA24204175', beta, est, X_test)
}

